import { formatPrice } from "./parseLetter.js";
import { collectLevels, isAlwaysOn, roleCode, shortLabel, levelScore } from "./chartLayout.js";

function pineString(value, max = 80) {
  const clean = String(value || "")
    .replace(/\\/g, "/")
    .replace(/"/g, "'")
    .replace(/\s+/g, " ")
    .trim();
  return clean.slice(0, max);
}

function pineTitle(parsed) {
  const bits = ["ES Roadmap", parsed.planDay, parsed.dateLabel].filter(Boolean);
  return pineString(bits.join(" — "), 48);
}

/**
 * Emit a paste-ready TradingView Pine v6 overlay.
 * Lines stop at the last bar (extend left only). Labels sit to the right,
 * skip neighbors inside minLabelGap, and zipper across three columns.
 */
export function buildPine(parsed, session = {}) {
  const levels = collectLevels(parsed);
  const labelOrder = [...levels]
    .filter((level) => level.major || isAlwaysOn(level))
    .sort((a, b) => levelScore(b) - levelScore(a) || b.price - a.price);

  const lineCalls = levels
    .map((level) => {
      const major = level.major ? "true" : "false";
      const always = isAlwaysOn(level) ? "true" : "false";
      return `    dummy := addLine(${formatPrice(level.price)}, "${roleCode(level)}", ${major}, ${always})`;
    })
    .join("\n");

  const labelCalls = labelOrder
    .map((level) => {
      const want = "true";
      return `    dummy := addLabel(${formatPrice(level.price)}, "${roleCode(level)}", ${want}, "${pineString(shortLabel(level), 18)}")`;
    })
    .join("\n");

  const bull = pineString(parsed.bullCase || parsed.summary || "Defend listed support; continue higher.", 72);
  const bear = pineString(
    parsed.bear?.below
      ? `Bear below ${formatPrice(parsed.bear.below)}${parsed.bear.trigger ? ` / ${formatPrice(parsed.bear.trigger)} trigger` : ""}`
      : parsed.bearCase || "No letter bear case parsed.",
    72,
  );
  const targets = (parsed.targets || []).map(formatPrice).join("  ") || "—";
  const last = Number.parseFloat(session.last);
  const lastLine = Number.isFinite(last) ? formatPrice(last) : "—";
  const title = pineTitle(parsed);

  return `//@version=6
indicator("${title}", overlay = true, max_lines_count = 500, max_labels_count = 500, max_bars_back = 500)

// Generated by ES Daily Roadmap.
// Lines extend into history only, so they do not run through labels.
// Labels: one per cluster, then zipper across 3 columns on the right.

grp = "Roadmap"
showMinors    = input.bool(false, "Show minor levels", group = grp)
showLabels    = input.bool(true, "Show labels", group = grp)
showTable     = input.bool(true, "Show plan table", group = grp)
minLabelGap   = input.float(16.0, "Min label gap (points)", minval = 4.0, maxval = 80.0, step = 1.0, group = grp)
labelPad      = input.int(4, "Label gap from price (bars)", minval = 2, maxval = 20, group = grp)
staggerBars   = input.int(10, "Label column width (bars)", minval = 4, maxval = 30, group = grp)
labelRange    = input.float(80.0, "Only label within N pts of close (0 = all)", minval = 0.0, maxval = 2000.0, step = 10.0, group = grp)

colSupMaj = input.color(#26a69a, "Major support", group = "Colors")
colSup    = input.color(#4db6a8, "Minor support", group = "Colors")
colResMaj = input.color(#ef5350, "Major resistance", group = "Colors")
colRes    = input.color(#e57373, "Minor resistance", group = "Colors")
colSetup  = input.color(#f0c14b, "FBD / setup / invalidation", group = "Colors")

var line[]  levelLines  = array.new<line>()
var label[] levelLabels = array.new<label>()
var float[] labeledPx   = array.new<float>()
var table   planTable   = table.new(position.bottom_left, 1, 5, bgcolor = color.new(#0b1220, 12), border_width = 1, border_color = color.new(#8b9bb4, 70), frame_color = color.new(#8b9bb4, 70), frame_width = 1)

ink(string role, bool major) =>
    role == "S" ? (major ? colSupMaj : colSup) : role == "R" ? (major ? colResMaj : colRes) : colSetup

clearDrawings() =>
    if array.size(levelLines) > 0
        for i = 0 to array.size(levelLines) - 1
            line.delete(array.get(levelLines, i))
        array.clear(levelLines)
    if array.size(levelLabels) > 0
        for j = 0 to array.size(levelLabels) - 1
            label.delete(array.get(levelLabels, j))
        array.clear(levelLabels)
    array.clear(labeledPx)
    0

addLine(float px, string role, bool major, bool always) =>
    bool show = always or major or showMinors
    if show
        color col = ink(role, major)
        int w = major or always ? 2 : 1
        // Stop at the last bar; extend.left keeps the ray in history, not through labels.
        line ln = line.new(bar_index, px, bar_index, px, xloc = xloc.bar_index, extend = extend.left, color = color.new(col, major or always ? 0 : 35), width = w, style = major or always ? line.style_solid : line.style_dotted)
        array.push(levelLines, ln)
    0

tooClose(float px) =>
    bool clash = false
    if array.size(labeledPx) > 0
        for k = 0 to array.size(labeledPx) - 1
            if math.abs(px - array.get(labeledPx, k)) < minLabelGap
                clash := true
    clash

addLabel(float px, string role, bool want, string txt) =>
    bool inRange = labelRange <= 0 or math.abs(px - close) <= labelRange
    if showLabels and want and inRange and not tooClose(px)
        color col = ink(role, true)
        int colN = array.size(levelLabels) % 3
        int x = bar_index + labelPad + colN * staggerBars
        label lb = label.new(x, px, txt, xloc = xloc.bar_index, style = label.style_label_left, color = color.new(#0b1220, 8), textcolor = col, size = size.tiny, textalign = text.align_left)
        array.push(levelLabels, lb)
        array.push(labeledPx, px)
    0

paintAll() =>
    dummy = clearDrawings()
${lineCalls || "    dummy := 0"}
${labelCalls || "    dummy := 0"}
    dummy

painted = 0
if barstate.islast
    painted := paintAll()

if showTable and barstate.islast
    table.cell(planTable, 0, 0, "${title}", text_color = color.white, text_size = size.small, bgcolor = color.new(#1b2433, 0))
    table.cell(planTable, 0, 1, "Last ${lastLine}", text_color = color.new(#c5d0e0, 0), text_size = size.tiny)
    table.cell(planTable, 0, 2, "Targets  ${pineString(targets, 48)}", text_color = color.new(#f0c14b, 0), text_size = size.tiny)
    table.cell(planTable, 0, 3, "Bull  ${bull}", text_color = color.new(#26a69a, 0), text_size = size.tiny)
    table.cell(planTable, 0, 4, "Bear  ${bear}", text_color = color.new(#ef5350, 0), text_size = size.tiny)
`;
}
