import { formatPrice } from "./parseLetter.js";

function pineString(value, max = 80) {
  const clean = String(value || "")
    .replace(/\\/g, "/")
    .replace(/"/g, "'")
    .replace(/\s+/g, " ")
    .trim();
  return clean.slice(0, max);
}

function pineTitle(parsed) {
  const bits = ["ES Roadmap", parsed.planDay, parsed.dateLabel].filter(Boolean);
  return pineString(bits.join(" — "), 48);
}

function roleCode(level) {
  if (level.role === "support") return "S";
  if (level.role === "resistance") return "R";
  return "X";
}

function labelFor(level) {
  const tags = [];
  if (level.major) tags.push("MAJ");
  if (level.fbd) tags.push("FBD");
  if (level.target) tags.push("TGT");
  if (level.shortSpot) tags.push("SH");
  if (level.invalidation) tags.push("INV");
  const tag = tags.length ? ` ${tags.join(" ")}` : "";
  return pineString(`${formatPrice(level.price)}${tag}`, 28);
}

function uniqueByPriceRole(levels) {
  const seen = new Set();
  const out = [];
  for (const level of levels) {
    const key = `${level.price}:${level.role}`;
    if (seen.has(key)) continue;
    seen.add(key);
    out.push(level);
  }
  return out;
}

/**
 * Emit a paste-ready TradingView Pine v6 overlay.
 * Drawings are rebuilt on the last bar so the script stays under plot() limits.
 */
export function buildPine(parsed, session = {}) {
  const levels = uniqueByPriceRole(
    [...(parsed.supports || []), ...(parsed.resistances || []), ...(parsed.extras || [])],
  ).sort((a, b) => b.price - a.price);

  const draws = levels
    .map((level) => {
      const major = level.major ? "true" : "false";
      const always =
        level.fbd || level.target || level.shortSpot || level.invalidation || level.role === "setup"
          ? "true"
          : "false";
      return `    dummy := drawLevel(${formatPrice(level.price)}, "${roleCode(level)}", ${major}, ${always}, "${labelFor(level)}")`;
    })
    .join("\n");

  const bull = pineString(parsed.bullCase || parsed.summary || "Defend listed support; continue higher.", 72);
  const bear = pineString(
    parsed.bear?.below
      ? `Bear below ${formatPrice(parsed.bear.below)}${parsed.bear.trigger ? ` / ${formatPrice(parsed.bear.trigger)} trigger` : ""}`
      : parsed.bearCase || "No letter bear case parsed.",
    72,
  );
  const targets = (parsed.targets || []).map(formatPrice).join("  ") || "—";
  const last = Number.parseFloat(session.last);
  const lastLine = Number.isFinite(last) ? formatPrice(last) : "—";
  const title = pineTitle(parsed);

  return `//@version=6
indicator("${title}", overlay = true, max_lines_count = 500, max_labels_count = 500, max_bars_back = 500)

// Generated by ES Daily Roadmap. Paste into TradingView → Pine Editor → Save → Add to chart.
// Toggle minors off if the chart feels noisy. FBD / target / short / invalidation levels always plot.

grp = "Roadmap"
showMinors   = input.bool(false, "Show minor levels", group = grp)
showLabels   = input.bool(true, "Show labels", group = grp)
showTable    = input.bool(true, "Show plan table", group = grp)
labelRight   = input.int(8, "Label offset (bars)", minval = 1, maxval = 50, group = grp)

colSupMaj = input.color(#26a69a, "Major support", group = "Colors")
colSup    = input.color(#4db6a8, "Minor support", group = "Colors")
colResMaj = input.color(#ef5350, "Major resistance", group = "Colors")
colRes    = input.color(#e57373, "Minor resistance", group = "Colors")
colSetup  = input.color(#f0c14b, "FBD / setup / invalidation", group = "Colors")

var line[]  levelLines  = array.new<line>()
var label[] levelLabels = array.new<label>()
var table   planTable   = table.new(position.top_right, 1, 5, bgcolor = color.new(#0b1220, 12), border_width = 1, border_color = color.new(#8b9bb4, 70), frame_color = color.new(#8b9bb4, 70), frame_width = 1)

clearDrawings() =>
    if array.size(levelLines) > 0
        for i = 0 to array.size(levelLines) - 1
            line.delete(array.get(levelLines, i))
        array.clear(levelLines)
    if array.size(levelLabels) > 0
        for j = 0 to array.size(levelLabels) - 1
            label.delete(array.get(levelLabels, j))
        array.clear(levelLabels)
    0

drawLevel(float px, string role, bool major, bool always, string txt) =>
    bool show = always or major or showMinors
    if show
        color col = role == "S" ? (major ? colSupMaj : colSup) : role == "R" ? (major ? colResMaj : colRes) : colSetup
        int w = major or always ? 2 : 1
        line ln = line.new(bar_index, px, bar_index + 1, px, xloc = xloc.bar_index, extend = extend.right, color = col, width = w, style = major ? line.style_solid : line.style_dotted)
        array.push(levelLines, ln)
        if showLabels
            label lb = label.new(bar_index + labelRight, px, txt, xloc = xloc.bar_index, style = label.style_label_left, color = color.new(col, 85), textcolor = col, size = size.small)
            array.push(levelLabels, lb)
    0

paintAll() =>
    dummy = clearDrawings()
${draws || "    dummy := 0"}
    dummy

painted = 0
if barstate.islast
    painted := paintAll()

if showTable and barstate.islast
    table.cell(planTable, 0, 0, "${title}", text_color = color.white, text_size = size.small, bgcolor = color.new(#1b2433, 0))
    table.cell(planTable, 0, 1, "Last ${lastLine}", text_color = color.new(#c5d0e0, 0), text_size = size.tiny)
    table.cell(planTable, 0, 2, "Targets  ${pineString(targets, 48)}", text_color = color.new(#f0c14b, 0), text_size = size.tiny)
    table.cell(planTable, 0, 3, "Bull  ${bull}", text_color = color.new(#26a69a, 0), text_size = size.tiny)
    table.cell(planTable, 0, 4, "Bear  ${bear}", text_color = color.new(#ef5350, 0), text_size = size.tiny)
`;
}
